name: waste_management
description: "Waste Management Tracking App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Storage and File Management
  permission_handler: ^11.4.0
  open_file: ^3.5.10
  path_provider: ^2.1.2

  # Notifications
  flutter_local_notifications: ^16.3.0

  # Data Persistence
  shared_preferences: ^2.2.2

  # Charts and Reports
  fl_chart: ^0.63.0
  pdf: ^3.10.4

  # UI Enhancements
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  qr_flutter: ^4.1.0
  image: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true




